# .github/workflows/data_pipeline.yml

name: Genomic Data Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_and_process_data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Generate synthetic genomic data (if not already in the repo)
      - name: Generate synthetic genomic data
        run: |
          python data_generation.py  # This generates the 'synthetic_genomic_data.csv' file

      # Run data processing and analysis
      - name: Run data analysis
        run: |
          python analysis.py  # This will read and process the 'cleaned_genomic_data.csv'

      # Run the visualization script
      - name: Run visualizations
        run: |
          python visualize.py  # This will generate visualizations and save them to './visualizations/'

      # Upload visualizations as artifact
      - name: Upload visualizations as artifact
        uses: actions/upload-artifact@v3
        with:
          name: visualizations
          path: ./visualizations/*.png  # Ensure this path points to your visualizations directory
          if-no-files-found: warn  # Don't fail the workflow if no files are found
